version: "3.7"
services:
  db:
    container_name: mssql2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "strong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - 9433:1433
    volumes:
      - mssql-volume:/var/opt/mssql
volumes:
  mssql-volume:
